type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start_Process:
      type: "start"
      transitions:
        unconditional:
        - "Create Table"
      parameters:
        componentName: "Start_Process"
    Create Table:
      type: "create-table-v2"
      transitions:
        success:
        - "S3 Load"
      parameters:
        componentName: "Create Table"
        createMethod: "Create If Not Exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "Customers"
        snowflakeTableType: "Permanent"
        columns:
        - - "CustomerID"
          - "NUMBER"
          - "5"
          - ""
          - ""
          - "Yes"
          - "Yes"
          - ""
          - ""
        - - "LastName"
          - "VARCHAR"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "FirstName"
          - "VARCHAR"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "BirthDate"
          - "VARCHAR"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Gender"
          - "VARCHAR"
          - "10"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "ParticipantType"
          - "VARCHAR"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "RegionID"
          - "NUMBER"
          - "5"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "MaritalStatus"
          - "VARCHAR"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation:
        primaryKeys:
        - "CustomerID"
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://analyticsmatillion/customerdata/demo_customers(20250817_190531).csv"
        pattern: ".*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Customers"
        loadColumns:
        - "CustomerID"
        - "LastName"
        - "FirstName"
        - "BirthDate"
        - "Gender"
        - "ParticipantType"
        - "RegionID"
        - "MaritalStatus"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "True"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "True"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start_Process:
      position:
        x: -560
        "y": -10
      tempMetlId: 1
    Create Table:
      position:
        x: -400
        "y": -10
      tempMetlId: 2
    S3 Load:
      position:
        x: -240
        "y": -10
      tempMetlId: 3
