type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create Table"
      parameters:
        componentName: "Start"
    Create Table:
      type: "create-table-v2"
      transitions:
        success:
        - "S3 Load"
      parameters:
        componentName: "Create Table"
        createMethod: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "Employee"
        snowflakeTableType: "Permanent"
        columns:
        - - "Employee_ID"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Full_Name"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Job_Title"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Department"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Business_Unit"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Gender"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Ethnicity"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Age"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Hire Date"
          - "TIMESTAMP_NTZ"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Annual_Salary"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Bonus%"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Country"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "City"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Exit_Date"
          - "VARCHAR"
          - "2000"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation:
        primaryKeys:
        - "Employee_ID"
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://analyticsmatillion/EC1.csv"
        pattern: ".*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Employee"
        loadColumns:
        - "Employee_ID"
        - "Full_Name"
        - "Job_Title"
        - "Department"
        - "Business_Unit"
        - "Gender"
        - "Ethnicity"
        - "Age"
        - "Hire Date"
        - "Annual_Salary"
        - "Bonus%"
        - "Country"
        - "City"
        - "Exit_Date"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "True"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "True"
        fieldOptionallyEnclosed: "\""
        nullIf:
        errorOnColumnCountMismatch: "True"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "True"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -530
        "y": -110
      tempMetlId: 1
    Create Table:
      position:
        x: -370
        "y": -110
      tempMetlId: 2
    S3 Load:
      position:
        x: -210
        "y": -110
      tempMetlId: 3
